"""Machine-readable NEW / LEGACY component ownership registry."""

# Architecture: SHARED

from __future__ import annotations


COMPONENT_CATEGORIES = {
    "__init__": "LEGACY",
    "admin_config": "SHARED",
    "application": "BRIDGE",
    "architecture_boundary": "SHARED",
    "backup_preflight_v2": "NEW",
    "backup_catalog_v2": "NEW",
    "chain_schedule_v2": "NEW",
    "bootstrap": "BRIDGE",
    "bundle": "SHARED",
    "capacity": "LEGACY",
    "capacity_adapter_v2": "NEW",
    "cli": "SHARED",
    "clock": "SHARED",
    "command": "SHARED",
    "config": "SHARED",
    "daemon": "SHARED",
    "engine": "LEGACY",
    "executor": "LEGACY",
    "executor_v2": "NEW",
    "libvirt_backend": "SHARED",
    "libvirt_execution": "LEGACY",
    "local_backup_v2": "NEW",
    "local_api": "SHARED",
    "models": "LEGACY",
    "physical_delete_adapter_v2": "NEW",
    "planner": "LEGACY",
    "purge_adapter_v2": "NEW",
    "received_catalog_v2": "NEW",
    "received_restore_v2": "NEW",
    "receiver_authkeys": "SHARED",
    "receiver_catalog": "SHARED",
    "receiver_publish": "SHARED",
    "receiver_reclaim_delete": "SHARED",
    "receiver_resolver": "SHARED",
    "receiver_restore": "SHARED",
    "receiver_seed": "SHARED",
    "receiver_session": "SHARED",
    "receiver_shell": "SHARED",
    "receiver_transfer": "SHARED",
    "reclaim_execution": "LEGACY",
    "reclaim_executor_v2": "NEW",
    "recovery_executor_v2": "NEW",
    "recovery_policy_v2": "NEW",
    "recovery_queue_v2": "NEW",
    "remote_restore": "LEGACY",
    "replica_sender": "LEGACY",
    "replica_v2": "NEW",
    "replica_worker": "LEGACY",
    "repository": "BRIDGE",
    "repository_v2": "NEW",
    "restore_libvirt": "SHARED",
    "restore_local": "SHARED",
    "restore_runtime": "LEGACY",
    "retention": "LEGACY",
    "retention_execution": "LEGACY",
    "runtime": "BRIDGE",
    "runtime_v2": "NEW",
    "scheduler": "LEGACY",
    "scheduler_v2": "NEW",
    "schema": "LEGACY",
    "schema_v2": "NEW",
    "serialization": "BRIDGE",
    "ssh_identity": "SHARED",
    "ssh_known_hosts": "SHARED",
    "ssh_preflight": "SHARED",
    "ssh_receiver": "SHARED",
    "ssh_storage_discovery": "SHARED",
    "state_machine": "LEGACY",
    "state_machine_v2": "NEW",
    "storage": "SHARED",
    "storage_prepare": "SHARED",
    "version": "SHARED",
}

VALID_CATEGORIES = frozenset({"NEW", "LEGACY", "BRIDGE", "SHARED", "UNKNOWN"})
